*.sink.prometheus.enabled=true
*.sink.prometheus.path=/metrics/prometheus
*.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet

master.sink.prometheus.enabled=true
master.sink.prometheus.path=/metrics/prometheus
master.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet

worker.sink.prometheus.enabled=true
worker.sink.prometheus.path=/metrics/prometheus
worker.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet

driver.sink.prometheus.enabled=true
driver.sink.prometheus.path=/metrics/prometheus
driver.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet

executor.sink.prometheus.enabled=true
executor.sink.prometheus.path=/metrics/prometheus
executor.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet

application.sink.prometheus.enabled=true
application.sink.prometheus.path=/metrics/prometheus
application.sink.prometheus.class=org.apache.spark.metrics.sink.PrometheusServlet