*.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink

master.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink

worker.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink

driver.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink

executor.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink

application.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink