rules:
# Spark Master gauges
- pattern: 'metrics<name=master\.(.+), type=gauges><>Value'
  name: spark_master_$1
  type: GAUGE

# Spark Worker gauges
- pattern: 'metrics<name=worker\.(.+), type=gauges><>Value'
  name: spark_worker_$1
  type: GAUGE

# Spark Driver gauges
- pattern: 'metrics<name=driver\.(.+), type=gauges><>Value'
  name: spark_driver_$1
  type: GAUGE

# Spark Executor gauges
- pattern: 'metrics<name=executor\.(.+), type=gauges><>Value'
  name: spark_executor_$1
  type: GAUGE

# Spark Application gauges
- pattern: 'metrics<name=application\.(.+), type=gauges><>Value'
  name: spark_application_$1
  type: GAUGE

# Spark Master counters
- pattern: 'metrics<name=master\.(.+), type=counters><>Count'
  name: spark_master_$1_total
  type: COUNTER

# Spark Worker counters
- pattern: 'metrics<name=worker\.(.+), type=counters><>Count'
  name: spark_worker_$1_total
  type: COUNTER