global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "airflow"
    static_configs:
      - targets: ["airflow-webserver:8080"]

  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]

  - job_name: "spark-worker"
    static_configs:
      - targets: ["spark-worker-1:8081"]